### PR TITLE
Introduces creation of IAM role + support for max_age_in_days

### LINKED ISSUE #34: Support application version lifecycle max_age_in_days option
## Describe the Feature

Requesting that support be added for `aws_elastic_beanstalk_application`'s `max_age_in_days` application version lifecycle option. It is similar to the `max_count` option which is supported by `appversion_lifecycle_max_count` in CloudPosse's `elastic-beanstalk-application` module.

See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elastic_beanstalk_application#max_age_in_days

## Expected Behavior

The CloudPosse `elastic-beanstalk-application` module should provide an option to set `aws_elastic_beanstalk_application`'s `max_age_in_days` option.

## Use Case

The `max_age_in_days` application version lifecycle option allows you to remove old versions based on age, rather than based on the *number* of versions accumulated.

## Alternatives Considered

Could potentially set the `max_age_in_days` via the AWS Console or CLI.

### LINKED ISSUE #43: Create IAM role for application version cleanup
### Describe the Feature

Add option to create IAM role which will be used for application version cleanup. 

### Expected Behavior

If user set option for creation IAM role, role should be created and lifecycle `appversion_lifecycle` will be configured in the same way as it is configured if user provided ARN of existing IAM role.

### Use Case

User wants to enable  `appversion_lifecycle` but doesn't want to create an IAM role in advance.

### Describe Ideal Solution

Introduce a new boolean variable which will be `false` by default. If set, a new IAM role will be created and passed its Arn to `appversion_lifecycle`.

### Alternatives Considered

Create an IAM role before calling the module.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aleksandarknezevic**
## what

- Introduces creation of IAM role for application version cleanup.
- Adds support for max_age_in_days

## why

- Users should have an option to create an IAM role
- Users should have an option to do cleanup based on time

## references

- closes #43
- closes #34

### CODE REVIEW

**Comment by hans-d** [comment]
@aleksandarknezevic hi, can you update this pr so that all tests pass? otherwise this PR  will be closed due to staleness. thanks!

**Comment by aleksandarknezevic** [comment]
@hans-d Thank you fixed. 
Notice: In this PR is already included fix for open PR #45

**Review by hans-d — APPROVED** [review]

**Comment by hans-d** [comment]
@aleksandarknezevic many thanks

**Pull request merged**
